# -*- coding: utf-8 -*-
"""AALab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xt1c7JuCbZozUATy0bASK3xheM0tpQPb
"""

# Bubble Sort
def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        # Last i elements are already in place
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]  # swap
    return arr
data = [64, 25, 12, 22, 11]
print("Bubble Sort:", bubble_sort(data.copy()))

# Selection Sort
def selection_sort(arr):
    n = len(arr)
    for i in range(n):
        min_index = i
        for j in range(i+1, n):
            if arr[j] < arr[min_index]:
                min_index = j
        arr[i], arr[min_index] = arr[min_index], arr[i]  # swap
    return arr
data = [64, 25, 12, 22, 11]
print("Selection Sort:", selection_sort(data.copy()))

# Insertion Sort
def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j+1] = arr[j]
            j -= 1
        arr[j+1] = key
    return arr
data = [64, 25, 12, 22, 11]

# Example usage
print("Original:", data)
print("Insertion Sort:", insertion_sort(data.copy()))